### PR TITLE
only pass keys down newBlocks chan in bitswap

### LINKED ISSUE #3262: Panic while running daemon
#### Version information: 
master

#### Type:
Panic

#### Priority:
P1

#### Description:
Got a panic while running the daemon.

```
Initializing daemon...
Swarm listening on /ip4/10.5.8.247/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: runtime error: index out of range

goroutine 95 [running]:
panic(0xc00500, 0xc420010110)
        /home/whyrusleeping/go/src/runtime/panic.go:500 +0x1a1
github.com/ipfs/go-ipfs/merkledag.(*Node).getPBNode(0xc42502c4b0, 0xc42023ec88)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/merkledag/coding.go:61 +0x33f
github.com/ipfs/go-ipfs/merkledag.(*Node).Marshal(0xc42502c4b0, 0xc422c3e760, 0xc422c3e760, 0x11387e0, 0xc422c3e760, 0x2)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/merkledag/coding.go:45 +0x2f
github.com/ipfs/go-ipfs/merkledag.(*Node).EncodeProtobuf(0xc42502c4b0, 0x0, 0x3, 0x22, 0x22, 0x22, 0x30)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/merkledag/coding.go:80 +0xb3
github.com/ipfs/go-ipfs/merkledag.(*Node).Multihash(0xc42502c4b0, 0xc42023ed98, 0x449915, 0xc42023eda8)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/merkledag/node.go:271 +0x34
github.com/ipfs/go-ipfs/merkledag.(*Node).Key(0xc42502c4b0, 0xc420063020, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/merkledag/node.go:249 +0x2b
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).provideCollector(0xc420234a00, 0x113ae20, 0xc420130d80)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:138 +0x2c4
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).startWorkers.func4(0x113f840, 0xc42019cde0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x3c
gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess.(*process).Go.func1(0xc4208fe980, 0xc42019cde0, 0xc42019cf00)
        /home/whyrusleeping/gopkg/src/gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess/impl-mutex.go:112 +0x3c
created by gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess.(*process).Go
        /home/whyrusleeping/gopkg/src/gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess/impl-mutex.go:115 +0x375
```

### PR DESCRIPTION
**Pull request by whyrusleeping**
should fix #3262 #3199 and #3246 

License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
cc @Kubuxu for review

File: exchange/bitswap/bitswap.go [hunk 1]
```diff
@@ -308,12 +308,17 @@ func (bs *Bitswap) HasBlock(blk blocks.Block) error {
 		return err
 	}
 
+	// NOTE: There exists the possiblity for a race condition here.  If a user
```
Comment (Kubuxu) [inline exchange/bitswap/bitswap.go]: Can you create issue for that?

**Comment by Kubuxu** [comment]
LGTM.

File: exchange/bitswap/bitswap.go [hunk 2]
```diff
@@ -137,7 +137,7 @@ type Bitswap struct {
 
 	process process.Process
 
-	newBlocks chan blocks.Block
+	newBlocks chan key.Key
```
Comment (Kubuxu) [inline exchange/bitswap/bitswap.go]: Maybe rename to newKeys?
but current name also fits.

**Comment by Kubuxu** [comment]
Two comments but generally LGTM

File: exchange/bitswap/bitswap.go (hunk 1 above)
Comment (whyrusleeping) [inline exchange/bitswap/bitswap.go]: Created: https://github.com/ipfs/go-ipfs/issues/3274

File: exchange/bitswap/bitswap.go (hunk 2 above)
Comment (whyrusleeping) [inline exchange/bitswap/bitswap.go]: Yeah, newBlocks still makes sense to me. I'm going to keep it as is
