### PR TITLE
check arguments after handling help

### LINKED ISSUE #4837: --help is broken for commands that require an argument that can be read from stdin
Unfortunately, we try to read the argument from stdin *before* parsing the help flag. To reproduce, run `ipfs dht provide --help`.

### PR DESCRIPTION
**Pull request by Stebalien**
otherwise, we block on required arguments from stdin before processing the help flag.

fixes #4837

### CODE REVIEW

File: test/sharness/t0100-name.sh [hunk 1]
```diff
@@ -99,6 +99,12 @@ test_expect_success "'ipfs name publish' fails" '
   printf '' | test_expect_code 1 ipfs name publish >publish_out 2>&1
 '
 
+test_expect_success "'ipfs name publish --help' succeeds" '
+  PEERID=`ipfs id --format="<id>"` &&
```
Comment (whyrusleeping) [inline test/sharness/t0100-name.sh]: whats with the ipfs id check?

Comment (Stebalien) [reply test/sharness/t0100-name.sh]: Copied from the other tests. I have no idea but I assume it's to make sure that publishing would otherwise work (although I guess it shouldn't really be necessary in this case).

Comment (Stebalien) [reply test/sharness/t0100-name.sh]: (fixed, and put the tests in the correct order)

**Comment by whyrusleeping** [comment]
Alright, @Kubuxu @magik6k @VictorBjelkholm does this one look good still?
