### PR TITLE
various ping fixes

### LINKED ISSUE #4542: ipfs ping self
Pinging the local peer does not work.

> ipfs id
```
{
        "ID": "Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
        "PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvxmCwAStFBFbsjkbokFRc3RN/OtzGdOEmMBlXewoFNu1RPtnzdUq/l5aNd2DD4pocDdSMV4GNNR1YxgqNyzNMxVC2nt+ziV4G/STMHx7XFWfVlRHiGMx/jm3m146x2PCtAnf+93EdihCEehdvz1zyNTwjGesO7XWAIC9tc7Qq9mYBe4tlY2a7a6SdBWwseAolNFMZkP9J0gdosjfFjcBEWmxwRxvTMTpCOuBv34KwiXQxzLEnby4GWtdvEgXrCMM9JLRlSSBlvqu+ro0MIejXk5lnRMr7hQRrjyqqMorntEXkoEYYXo663t5HxaIie3bjAC6nXouzfzntA/AEp7gzAgMBAAE=",
        "Addresses": [
                "/ip4/169.254.243.5/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
                "/ip4/169.254.127.178/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
                "/ip4/192.168.178.21/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
                "/ip4/169.254.88.5/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
                "/ip4/127.0.0.1/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
                "/ip6/2406:e001:144b:1:7573:b0a8:46b0:bfea/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
                "/ip6/2406:e001:144b:1:c9b9:c8a7:93fa:db8f/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa",
                "/ip6/::1/tcp/4001/ipfs/Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa"
        ],
        "AgentVersion": "go-ipfs/0.4.13/",
        "ProtocolVersion": "ipfs/0.1.0"
}
```
> ipfs ping Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa
```
Looking up peer Qmei6fBYij8gjbetgHLXmoR54iRc9hioPR7dtmBTNG3oWa
Peer lookup error: routing: not found
```

### PR DESCRIPTION
**Pull request by Stebalien**
* Return an error when pinging self (an alternative would be to fake the ping). fixes #4542.
* Better error messages.
* Return an error if the ping count is <= 0.

### CODE REVIEW

File: test/sharness/t0041-ping.sh [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+startup_cluster 2
+
+test_expect_success 'peer ids' '
+  PEERID_0=$(iptb get id 0) &&
+  PEERID_1=$(iptb get id 1)
+'
+
+test_expect_success "test ping other" '
+  ipfsi 0 ping -n2 -- "$PEERID_1" && ipfsi 1 ping -n2 -- "$PEERID_0"
```
Comment (whyrusleeping) [inline test/sharness/t0041-ping.sh]: put each of these on its own line for readability

**Comment by Stebalien** [comment]
@whyrusleeping picky picky... done.

**Comment by whyrusleeping** [comment]
@Stebalien <3 <3 <3 <3 <3 <3 <3
