### PR TITLE
cmd/pubsub: fix peers command topic filtering

### LINKED ISSUE #3467: Pubsub returns wrong peers for a topic
#### Version information:

0.4.5-pre1

#### Type:

Bug

#### Description:

When I call pubsub/peers(topic), go-ipfs returns all peers that are connected to it. Expected behaviour is to return only the ones that are subscribed to the specified topic.

### PR DESCRIPTION
**Pull request by whyrusleeping**
closes #3467 

License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

File: core/commands/pubsub.go [hunk 1]
```diff
@@ -302,8 +305,13 @@ To use, the daemon must be run with '--enable-pubsub-experiment'.
 			return
 		}
 
+		var topic string
+		if len(req.Arguments()) == 1 {
```
Comment (Kubuxu) [inline core/commands/pubsub.go]: This will cause confusion if more topics are passed. IMO either error out or use all of them.
