### PR TITLE
Correctly set the content type for `object get --encoding=protobuf`

### LINKED ISSUE #2469: `ipfs object get --encoding=protobuf`HTTP response returns wrong content type
```
$ curl -i -X POST "http://localhost:5001/api/v0/object/get?arg=QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ&encoding=protobuf"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output
Content-Type: application/json
Server: go-ipfs/0.4.0-dev
Trailer: X-Stream-Error
Transfer-Encoding: chunked
Date: Tue, 15 Mar 2016 17:11:30 GMT
Transfer-Encoding: chunked

1
" ? :?^?E???p??\?|?.??t|d??U??cat.jpg?
```

The `Content-Type` should be `application/protobuf`, not `application/json`.

### PR DESCRIPTION
**Pull request by Stebalien**
It used to default to `application/json` but is now correctly set to
`application/protobuf`.

fixes #2469

License: MIT
Signed-off-by: Steven Allen <steven@stebalien.com>

### CODE REVIEW

**Comment by Stebalien** [comment]
Unfortunately, I have no idea why my test cases are failing. They when I run them manually.

File: test/sharness/t0051-object.sh [hunk 1]
```diff
@@ -43,6 +43,26 @@ test_object_cmd() {
 		ipfs object get $HASH >actual_getOut
 	'
 
+	test_expect_success "'ipfs object get --encoding=protobuf' returns the correct content type" '
+		HASH="QmWkHFpYBZ9mpPRreRbMhhYWXfUhBAue3JkbbpFqwowSRb" &&
+    curl -sI "http://$API_ADDR/api/v0/object/get?arg=$HASH&encoding=protobuf" | grep -q "^Content-Type:\s*application/protobuf"
+  '
+
+	test_expect_success "'ipfs object get --encoding=json' returns the correct content type" '
+		HASH="QmWkHFpYBZ9mpPRreRbMhhYWXfUhBAue3JkbbpFqwowSRb" &&
```
Comment (whyrusleeping) [inline test/sharness/t0051-object.sh]: You don't need to re-set the `HASH` variable in each scope. shell variables like this are global(ish)

Comment (Stebalien) [inline test/sharness/t0051-object.sh]: That's what I did the first time around but it still failed. 
-- 
Steven Allen

**Comment by Stebalien** [comment]
> Unfortunately, I have no idea why my test cases are failing. They when I run them manually.

I didn't realize those tests were run offline as well...

**Comment by Stebalien** [comment]
I'm pretty sure the other failing tests are not my fault.

**Comment by RichardLitt** [comment]
Also subscribing.

**Comment by whyrusleeping** [comment]
@noffle i assigned another related PR to you, so i'm gonna assign this one as well

**Comment by Kubuxu** [comment]
LGTM, the change looks much bigger than it is because golang indenting changes but it is really very small change.

**Comment by whyrusleeping** [comment]
LGTM, great to finally have this merged in

**Comment by RichardLitt** [comment]
Does this only apply to `object get`?

**Comment by Stebalien** [comment]
@RichardLitt Yes. Are there any other endpoints that return protocol buffers?

**Comment by RichardLitt** [comment]
@Stebalien Looked again; not that I could see. Sweet.
