### PR TITLE
make repo size test pass deterministically

### LINKED ISSUE #4408: RepoSize incorrect with symlink
Interesting sharness error:

```
make: *** [test/sharness/t0088-repo-stat-symlink.sh] Error 1
make: *** Waiting for unfinished jobs....
*** test/sharness/t0088-repo-stat-symlink.sh ***
# TEST_VERBOSE=1
# TEST_NO_FUSE=1
# TEST_NO_PLUGIN=
# TEST_EXPENSIVE=1
# TEST_OS=LINUX
expecting success: 
  mkdir sym_link_target &&
  ln -s sym_link_target .ipfs

ok 1 - create symbolic link for IPFS_PATH

expecting success: 
    export IPFS_PATH="$(pwd)/.ipfs" &&
    ipfs init --profile=test -b=1024 > /dev/null
  
ok 2 - ipfs init succeeds

expecting success: 
    mkdir mountdir ipfs ipns &&
    test_config_set Mounts.IPFS "$(pwd)/ipfs" &&
    test_config_set Mounts.IPNS "$(pwd)/ipns" ||
    test_fsh cat "\"$IPFS_PATH/config\""
  
ipfs config  "Mounts.IPFS" "/go/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0088-repo-stat-symlink.sh/ipfs"
ipfs config  "Mounts.IPNS" "/go/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0088-repo-stat-symlink.sh/ipns"
ok 3 - prepare config -- mounting

expecting success: 
  export IPFS_PATH="sym_link_target" &&
  reposize_direct=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
  export IPFS_PATH=".ipfs" &&
  reposize_symlink=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
  test $reposize_symlink -ge $reposize_direct

not ok 4 - 'ipfs repo stat' RepoSize is correct with sym link
#	
#	  export IPFS_PATH="sym_link_target" &&
#	  reposize_direct=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
#	  export IPFS_PATH=".ipfs" &&
#	  reposize_symlink=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
#	  test $reposize_symlink -ge $reposize_direct
#	

# failed 1 among 4 test(s)
1..4
test/sharness/Rules.mk:31: recipe for target 'test/sharness/t0088-repo-stat-symlink.sh' failed
```

### PR DESCRIPTION
**Pull request by Stebalien**
This test assumed that the repo could only grow in size when it can also shrink. This commit makes the test actually test for the specific bug it was meant to detect.

fixes #4408

### CODE REVIEW

File: test/sharness/t0088-repo-stat-symlink.sh [hunk 1]
```diff
@@ -22,7 +22,8 @@ test_expect_success "'ipfs repo stat' RepoSize is correct with sym link" '
   export IPFS_PATH=".ipfs" &&
   reposize_symlink=$(ipfs repo stat | grep RepoSize | awk '\''{ print $2 }'\'') &&
   echo "reposize_symlink: $reposize_symlink;  reposize_direct: $reposize_direct" &&
-  test $reposize_symlink -ge $reposize_direct
+  reposize_diff="$(( $reposize_symlink - $reposize_direct ))" &&
+  test "${reposize_diff#-}" -lt 2048 # less than 2k diff
 '
```
Comment (kevina) [inline test/sharness/t0088-repo-stat-symlink.sh]: Any particular reason for choosing "2048" as the threshold?

Comment (Stebalien) [reply test/sharness/t0088-repo-stat-symlink.sh]: 1k was too small in my testing.

Comment (kevina) [reply test/sharness/t0088-repo-stat-symlink.sh]: I am thinking the threshold should be larger.  If there was a symbolic link that was not followed then I image either 1) there will be an error or 2) the size will be 0 or something very close to it...

Comment (leerspace) [reply test/sharness/t0088-repo-stat-symlink.sh]: Prior to the PR to add support for symbolic links, the RepoSize for a symbolic link .ipfs path was non-zero but small. I don't remember exactly what it was but I think it was <100 bytes.

Comment (Stebalien) [reply test/sharness/t0088-repo-stat-symlink.sh]: In that case, the correct fix would probably be to just check if the repo-size (as seen via a symlink) is over 1KiB. Sound good?

Comment (kevina) [reply test/sharness/t0088-repo-stat-symlink.sh]: I would test @leerspace assumption first by undue his change and seeing what size is reported.  But otherwise that sounds good.

Comment (Stebalien) [reply test/sharness/t0088-repo-stat-symlink.sh]: Tested and fixed. I'm now testing to make sure that the repo size is greater than the size of the symlink itself.

Comment (kevina) [reply test/sharness/t0088-repo-stat-symlink.sh]: That seams a little overly specific, but if that the size that was being reported before it LGTM.

Comment (Stebalien) [reply test/sharness/t0088-repo-stat-symlink.sh]: I could just choose some arbitrary minimum but this is really what we're trying to test.

**Comment by Stebalien** [comment]
You know... cross platform shell scripts are a real pain.

File: test/sharness/t0088-repo-stat-symlink.sh (hunk 1 above)
Comment (kevina) [reply test/sharness/t0088-repo-stat-symlink.sh]: Either way is fine by me.
