### PR TITLE
fix truncating when already at the correct size

### LINKED ISSUE #4518: MFS truncate with an offset greater than the length of the file panics.
This *should* either return an error or extend the size of the file. The bug is in `dagTruncate` in the dagmodifier. It assumes that there *is* a node to truncate.

### PR DESCRIPTION
**Pull request by schomatis**
Fixes #4518.

(Taken from PR https://github.com/ipfs/go-ipfs/pull/4517.)

### CODE REVIEW

**Comment by schomatis** [comment]
@whyrusleeping Need to get this merged to add the "truncate at same size" test in https://github.com/ipfs/go-ipfs/pull/5216#issuecomment-405782238.

File: mfs/mfs_test.go [hunk 1]
```diff
@@ -1111,3 +1111,28 @@ func TestFileDescriptors(t *testing.T) {
 		t.Fatal(err)
 	}
 }
+
+func TestTruncateAtSize(t *testing.T) {
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+	ds, rt := setupRoot(ctx, t)
+
+	dir := rt.GetValue().(*Directory)
```
Comment (Stebalien) [inline mfs/mfs_test.go]: Needs fix for rebase.

**Comment by schomatis** [comment]
Rebased, thanks!
