### PR TITLE
cmd: validate repo/api file and print nicer error message

### LINKED ISSUE #3191: bad error if $repodir/api file is bad/corrupted
Version/Platform/Processor information (from `ipfs version --all`):

0.4.3-rc3

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): commands
Priority (from P0: operations on fire, to P4: functioning): P4

Description:

bad error if $repodir/api file is bad/corrupted

``` sh
> rm ~/.ipfs/api # clear anything there
> touch ~/.ipfs/api # bad file
> ipfs daemon
Error:  is not a 'thin waist' address
```

It should be something like

```
> ipfs daemon
Error: failed to parse <path-to-repo/api file. If there is no daemon running, just delete it.
You can do this with:
    ps aux | grep ipfs  # check there is no ipfs daemon
    rm <path-to-repo>/api
```

### PR DESCRIPTION
**Pull request by Kubuxu**
Resolves #3191
License: MIT
Signed-off-by: Jakub Sztandera kubuxu@protonmail.ch

### CODE REVIEW

File: cmd/ipfs/main.go [hunk 1]
```diff
@@ -595,17 +594,24 @@ func profileIfEnabled() (func(), error) {
 // a running API service. if there is one, it returns a client.
 // otherwise, it returns errApiNotRunning, or another error.
 func getApiClient(repoPath, apiAddrStr string) (cmdsHttp.Client, error) {
-
-	if apiAddrStr == "" {
-		var err error
-		if apiAddrStr, err = fsrepo.APIAddr(repoPath); err != nil {
+	efmt := fmt.Sprintf("failed to parse %[1]s/api file.\n\terror: %%s\n"+
```
Comment (whyrusleeping) [inline cmd/ipfs/main.go]: lets make this a multiline string constant somewhere

File: cmd/ipfs/main.go [hunk 2]
```diff
@@ -595,17 +594,24 @@ func profileIfEnabled() (func(), error) {
...
+		if err != nil {
 			return nil, err
 		}
 	}
-
-	addr, err := ma.NewMultiaddr(apiAddrStr)
-	if err != nil {
-		return nil, err
+	if len(addr.Protocols()) == 0 {
+		return nil, fmt.Errorf(efmt, "multiaddr doesn't provide any protocols")
```
Comment (whyrusleeping) [inline cmd/ipfs/main.go]: While technically correct, i dont think this helps the user understand what to do

File: cmd/ipfs/main.go [hunk 3]
```diff
@@ -595,17 +594,24 @@ func profileIfEnabled() (func(), error) {
...
-		if apiAddrStr, err = fsrepo.APIAddr(repoPath); err != nil {
+	efmt := fmt.Sprintf("failed to parse %[1]s/api file.\n\terror: %%s\n"+
+		"If there is no daemon running, it is safe to delete it.\nYou can do it with:\n"+
+		"\tps aux | grep ipfs # check there is no ipfs daemon\n\trm %[1]s/api\n", repoPath)
+	var addr ma.Multiaddr
+	var err error
+	if len(apiAddrStr) != 0 {
+		addr, err = ma.NewMultiaddr(apiAddrStr)
+		if err != nil {
+			return nil, fmt.Errorf(efmt, err.Error)
```
Comment (Kubuxu) [inline cmd/ipfs/main.go]: This is also wrong, it should be line 609.

File: cmd/ipfs/main.go (hunk 2 above)
Comment (Kubuxu) [inline cmd/ipfs/main.go]: It doesn't, it is information for us/people that debug others set-ups.

**Comment by Kubuxu** [comment]
Updated

**Comment by Kubuxu** [comment]
Updated once more.

File: cmd/ipfs/main.go [hunk 4]
```diff
@@ -591,21 +590,37 @@ func profileIfEnabled() (func(), error) {
 	return func() {}, nil
 }
 
+var apiFileErrorFmt string = `Failed to parse %[1]s/api file.
+	error: %[2]s
+If there is no daemon running, it is safe to delete it.
+You can do it with:
+	ps aux | grep ipfs # check there is no ipfs daemon
```
Comment (whyrusleeping) [inline cmd/ipfs/main.go]: Not valid advice for windows... not sure what the best way to do this is.

cc @jbenet @lgierth

File: repo/fsrepo/fsrepo.go [hunk 5]
```diff
@@ -293,16 +295,21 @@ func APIAddr(repoPath string) (string, error) {
...
 	n, err := f.Read(buf)
 	if err != nil && err != io.EOF {
-		return "", err
+		return nil, err
 	}
 
 	s := string(buf[:n])
 	s = strings.TrimSpace(s)
-	return s, nil
+	m, err := ma.NewMultiaddr(s)
```
Comment (whyrusleeping) [inline repo/fsrepo/fsrepo.go]: should just `return ma.NewMultiaddr(s)` here

File: cmd/ipfs/main.go (hunk 4 above)
Comment (djdv) [inline cmd/ipfs/main.go]: On Windows that would be `tasklist | findstr ipfs`, alternatively you can defer people to the Task Manager.

Comment (lgierth) [inline cmd/ipfs/main.go]: thanks @djdv, I think something like this works:

```
If you're sure go-ipfs isn't running, you can just delete it.
Otherwise check:
	ps aux | grep ipfs # on Linux and OSX
	tasklist | findstr ipfs # on Windows

Comment (whyrusleeping) [inline cmd/ipfs/main.go]: We can also generate this message in an `init` function where we can do a switch on `runtime.GOOS`

**Comment by whyrusleeping** [comment]
@Kubuxu status update?

**Comment by Kubuxu** [comment]
I remember looking for a lib that we have already imported that included helpers for checking OSes, and then I did something else.

**Comment by Kubuxu** [comment]
Updated

File: cmd/ipfs/main.go [hunk 6]
```diff
@@ -32,7 +25,14 @@ import (
 	repo "github.com/ipfs/go-ipfs/repo"
 	config "github.com/ipfs/go-ipfs/repo/config"
 	fsrepo "github.com/ipfs/go-ipfs/repo/fsrepo"
+
+	logging "gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log"
+	"gx/ipfs/QmXuBJ7DR6k3rmUEKtvVMhwjmXDuJgXXPUt4LQXKBMsU93/go-os-helper"
```
Comment (whyrusleeping) [inline cmd/ipfs/main.go]: since the package name and the directory name arent the same, lets add `osh` to name this import.

File: cmd/ipfs/main.go [hunk 7]
```diff
@@ -591,21 +591,47 @@ func profileIfEnabled() (func(), error) {
...
-	}
 
-	addr, err := ma.NewMultiaddr(apiAddrStr)
-	if err != nil {
-		return nil, err
+		if err != nil {
+			return nil, fmt.Errorf(apiErrorFmt, repoPath, err.Error())
+		}
+	}
+	if len(addr.Protocols()) == 0 {
```
Comment (Kubuxu) [inline cmd/ipfs/main.go]: This happens when for some reason the API File is empty.

**Comment by Kubuxu** [comment]
Last commit should address it.

File: cmd/ipfs/main.go (hunk 7 above)
Comment (whyrusleeping) [inline cmd/ipfs/main.go]: Right, But theres no possible way we can end up with that scenario if the user passes in an api addr with `--api` right?

Comment (Kubuxu) [inline cmd/ipfs/main.go]: No idea that is why I added check in https://github.com/ipfs/go-ipfs/pull/3219/commits/7512eb93bdd749ee70048e933e8b015dfc8c2f27

File: package.json [hunk 8]
```diff
@@ -269,6 +269,12 @@
       "hash": "QmaUewj1HPiCX5mjNHmevQiNWr4eeAn7HBfHcGVbRyafdo",
       "name": "floodsub",
       "version": "0.6.2"
+	},
+	{
+      "author": "Kubuxu",
+      "hash": "QmXuBJ7DR6k3rmUEKtvVMhwjmXDuJgXXPUt4LQXKBMsU93",
+      "name": "go-os-helper",
+      "version": "0.0.0"
```
Comment (Kubuxu) [inline package.json]: oh, look at that

Comment (whyrusleeping) [inline package.json]: what am i looking at?

Comment (Kubuxu) [inline package.json]: Oh, ok, not it is good. Just a second ago GH wasn't showing the bracket that is bellow this line.

**Comment by whyrusleeping** [comment]
@Kubuxu wanna rebase this and make sure the tests pass?

**Comment by Kubuxu** [comment]
Rebased.

**Comment by Kubuxu** [comment]
Recreated it from ground 0 (easier than resolving conflicts in import section).

**Comment by Kubuxu** [comment]
@whyrusleeping should be good for merge right now
