### PR TITLE
when running an external command, only construct a node if running in online mode

### LINKED ISSUE #5191: repo migration failing when attempting to update to ipfs v0.4.16-rc1
#### Version information:
Current:
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/darwin
Golang version: go1.10.2

attempting to update to:
go-ipfs version: 0.4.16-rc1
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.2

#### Type:
Bug

#### Description:
Attempting to install `go-ipfs` v0.4.16-rc1 via the latest version of `ipfs-update` v1.5.3 and I am getting the following error. The ipfs daemon was not running whilst I ran `ipfs update install v0.4.16-rc1`.

```
$ ipfs update install v0.4.16-rc1                                                                                                                                                       
fetching go-ipfs version v0.4.16-rc1
binary downloaded, verifying...
success! tests all passed.
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
  check complete, migration required.
fetching fs-repo-migrations version v1.4.0
running migration: '/var/folders/kh/zhltnfr93bq3tl5n11vj3s680000gn/T/ipfs-update-migrate487519237/fs-repo-migrations -to 7 -y'
Found fs-repo version 6 at /Users/lanzafame/.ipfs
===> Running migration 6 to 7...
applying 6-to-7 repo migration
ipfs migration:  migration 6 to 7 failed: cannot acquire lock: Lock FcntlFlock of /Users/lanzafame/.ipfs/repo.lock failed: resource temporarily unavailable
ERROR: Migration Failed:  migration failed: exit status 1
install failed, reverting changes...
ERROR: migration failed: exit status 1
Error: exit status 1
```

Not sure if this is related to #5179 or fs-repo-migrations.

### PR DESCRIPTION
**Pull request by Stebalien**
This breaks commands like `ipfs update` that expect IPFS to *not* be running.

fixes #5191

### CODE REVIEW

File: core/commands/external.go [hunk 1]
```diff
@@ -52,8 +52,16 @@ func ExternalBinary() *cmds.Command {
 			// setup env of child program
 			env := os.Environ()
 
-			nd, err := req.InvocContext().GetNode()
-			if err == nil {
+			// Get the node iff already defined.
+			if req.InvocContext().Online {
+				nd, err := req.InvocContext().GetNode()
```
Comment (whyrusleeping) [inline core/commands/external.go]: we can probably just skip this `GetNode` call entirely and just use the `req.InvocContext().Online` value directly below for setting the variable

Comment (Stebalien) [reply core/commands/external.go]: I wanted to ensure we actually *created* the node. `Online` means "node will be constructed in online mode" but I don't know if it actually *constructs* the node. Actually, I'm pretty sure it doesn't.
