### PR TITLE
Fix #4996: Improve help text for "ipfs files cp"

### LINKED ISSUE #4996: ipfs files cp command help text inaccurate
The CLI help says that `ipfs files cp` can be used to copy files into mfs:

```sh
$ ipfs files cp --help
USAGE
  ipfs files cp <source> <dest> - Copy files into mfs.
```

It doesn't seem to work like that though:

```sh
$ ipfs files cp ./my-file.txt /my-file.txt
Error: paths must start with a leading slash
```

### PR DESCRIPTION
**Pull request by hsanjuan**
#4996

### CODE REVIEW

File: core/commands/files.go [hunk 1]
```diff
@@ -321,7 +321,23 @@ func walkBlock(ctx context.Context, dagserv ipld.DAGService, nd ipld.Node) (bool
 
 var filesCpCmd = &cmds.Command{
 	Helptext: cmds.HelpText{
-		Tagline: "Copy files into mfs.",
+		Tagline: "Copy any IPFS objects into mfs (or copy within MFS).",
```
Comment (Stebalien) [inline core/commands/files.go:324]: "objects" is a bit confusing. I'd say "copy ipfs files & directories into MFS".

Comment (hsanjuan) [reply core/commands/files.go]: I tend to agree. I have fixed this and aligned the flag descriptions (which also used "object")/
