### PR TITLE
Fix two race conditions (and possibly go routine leaks) in commands

### LINKED ISSUE #4405: Remove concurrent uses of `go-ipfs-cmds.ResponseEmitter`
It's *not* thread-safe.

* [ ] `core/commands/pin.go`: addPinCmd (concurrent SetError)
* [ ] `core/commands/add.go`: AddCmd (PostRun, concurrent SetError)

All other uses of SetError, SetOutput, and Emit appear to be fine.

### PR DESCRIPTION
**Pull request by Stebalien**
fixes #4405

### CODE REVIEW

File: core/commands/pin.go [hunk 1]
```diff
@@ -90,32 +90,31 @@ var addPinCmd = &cmds.Command{
 		v := new(dag.ProgressTracker)
 		ctx := v.DeriveContext(req.Context())
 
-		ch := make(chan []*cid.Cid)
+		type pinResult struct {
+			pins []*cid.Cid
+			err  error
+		}
```
Comment (keks) [inline core/commands/pin.go]: Huh, I did not know you could define types in functions. Neat!

Comment (Stebalien) [reply core/commands/pin.go]: You want to have some *real* fun?

```go
ch := make(chan struct{pins []*cid.Cid, err error}, 1)
//...
ch <- struct{pins []*cid.Cid, err error}{err: errors.New("😎")
```

Comment (Kubuxu) [reply core/commands/pin.go]: I have some other trick for you:

```go
type System struct {
    cntrSafe struct {
        sync.Mutex
        n int
    }
    mapSafe struct {
        sync.Mutex
        m map[int]int
    }
}
````
