### PR TITLE
Filter dials to blocked subnets, even when using DNS.

### LINKED ISSUE #6995: Address filtering is not working properly
#### Version information:

> master

#### Description:

Upstream issue: https://github.com/libp2p/go-libp2p/issues/841

Note 1: The tcp and websocket transports will close all such connections immediately without performing the libp2p handshake. However, QUIC connections will not be rejected.
Note 2: This does not affect any released versions of libp2p.

### PR DESCRIPTION
**Pull request by Stebalien**
* [x] Implement a test.
* [x] Fix the bug.

Fixes #6995

### CODE REVIEW

File: test/sharness/t0142-testfilter.sh [hunk 1]
```diff
@@ -0,0 +1,61 @@
+#!/usr/bin/env bash
+#
+# Copyright (c) 2014 Jeromy Johnson
+# MIT Licensed; see the LICENSE file in this repository.
+#
```
Comment (hsanjuan) [inline test/sharness/t0142-testfilter.sh]: Guess this needs a bump
