### PR TITLE
wait for all connections to close before exiting on shutdown.

### LINKED ISSUE #4055: Error message when shutting down ipfs daemon
#### Version information:
```
go-ipfs version: 0.4.10-4679f80
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3
```

#### Type:
error message without any noticeable error

#### Severity:
very low

#### Description:
I ran `ipfs shutdown` on the daemon, which had been started with `--writable`, and received the following error message (in the second terminal, not in the daemon's terminal).

```
Error: Post http://127.0.0.1:5001/api/v0/shutdown?encoding=json&stream-channels=true: EOF
```

Daemon shutdown worked nonetheless.

### PR DESCRIPTION
**Pull request by Stebalien**
Using httpServer.Shutdown will:

1. Close the listener (preventing new connections).
2. Close each connection as outstanding requests finish.

Turns out this issue wasn't as tricky as I had thought.

This prevent us from shutting down before outstanding requests get a chance to respond.

fixes #4055

### CODE REVIEW

File: core/commands/shutdown.go [hunk 1]
```diff
@@ -3,31 +3,28 @@ package commands
...
 
+	cmds "gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds"
 	"gx/ipfs/QmdE4gMduCKCGAcczM2F5ioYDfdeKuPix138wrES1YSr7f/go-ipfs-cmdkit"
-
-	cmds "github.com/ipfs/go-ipfs/commands"
 )
 
 var daemonShutdownCmd = &cmds.Command{
 	Helptext: cmdkit.HelpText{
 		Tagline: "Shut down the ipfs daemon",
```
Comment (magik6k) [inline core/commands/shutdown.go]: Maybe `Schedule shutdown of the ipfs daemon`?

Comment (Stebalien) [reply core/commands/shutdown.go]: Well, it *does* shut it down. This will:

1. Cancel in-progress requests.
2. Wait for the IPFS node to close.
3. Return.

Note: it won't actually *wait* for all in-progress requests to finish. That would deadlock.
