### PR TITLE
Nicer index

### LINKED ISSUE #1153: nicer looking index page
this is not so hot:

would be nice to have humanized sizes. and nice listings. and maybe have links to ipfs.

### LINKED ISSUE #1365: .. links in http proxy borked unless url ends with a slash
To reproduce:

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye

click b

click c

Now you should be at http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c

click ".."

This takes you to

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/

but should take you to http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b or maybe http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/

Explanation: the ".." link goes to "./..". The browsers interpret this differently depending on whether the URL ends with a slash or not. When navigating deeper into the file tree (eg from b -> c) the links do not end with /, and after doing that, the "./.." doesn't go to the right place.

To be clear, the ".." link works fine for this url:

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c/

But not this one:

http://gateway.ipfs.io/ipfs/QmWELkZ7N7CUByagkkGVKD7euc9w2f8F9fAX4E6cMi6wye/b/c

(the only difference being whether there's a "/" at the end or not).

This is particularly problematic, because the http proxy is generating urls like the latter.

### PR DESCRIPTION
**Pull request by cryptix**
This introduces @krl's new index page

TODO:
- [x] fixes #1153
- [x] file icon images are embedded inside css
- [x] fixes #1365 (back links)
- [x] where to we seed the assets? (ipfs/infrastructure#24)
- [x] add tests. Do we have known/mocked hashes to test this a little? Basically I just want to test 404 and rendering without errors. For testing the HTML we could use goquery

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0ad606f15bf9d84534df08702eb0d3e1d432875e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by cryptix** [comment]
squashed to one commit with signed-off-by

File: core/corehttp/gateway_indexPage.go [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+	ext := path.Ext(name)
+	_, ok := knownIcons[ext]
+	if !ok {
+		// default blank icon
+		return "ipfs-_blank"
+	}
+	return "ipfs-" + ext[1:] // slice of the first dot
+}
+
+var knownIcons = map[string]bool{
```
Comment (cryptix) [inline core/corehttp/gateway_indexPage.go]: I'm sure there is a nicer way to do this.

File: core/corehttp/gateway_indexPage.go [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+
+// Directory listing template
+var listingTemplate = template.Must(template.New("dir").Funcs(template.FuncMap{"iconFromExt": iconFromExt}).Parse(`
+<!DOCTYPE html>
+<html>
+		<head>
+				<meta charset="utf-8" />
+				<!-- TODO: seed these - maybe like the starter ex or the webui? -->
+				<link rel="stylesheet" href="/ipfs/QmXB7PLRWH6bCiwrGh2MrBBjNkLv3mY3JdYXCikYZSwLED/bootstrap.min.css"/>
+				<!-- helper to construct this is here: https://github.com/cryptix/exp/blob/master/imgesToCSSData/convert.go -->
```
Comment (cryptix) [inline core/corehttp/gateway_indexPage.go]: Is there a better place to put this helper?

File: core/corehttp/gateway_handler.go [hunk 3]
```diff
@@ -205,14 +181,36 @@ func (i *gatewayHandler) getOrHeadHandler(w http.ResponseWriter, r *http.Request
...
-
 		if r.Method != "HEAD" {
-			if err := i.dirList.Execute(w, hndlr); err != nil {
+			// construct the correct back link
+			// https://github.com/ipfs/go-ipfs/issues/1365
+			var backLink string = r.URL.Path
+
+			// don't go further up than /ipfs/$hash/
+			pathSplit := strings.Split(backLink, "/")
+			switch {
```
Comment (cryptix) [inline core/corehttp/gateway_handler.go]: Only the default case here is doing something. It could be turned into a large `if !(caseA) && !(caseB) {}` but I disliked the readability.

File: core/corehttp/gateway_handler.go [hunk 4]
```diff
@@ -205,14 +181,36 @@ func (i *gatewayHandler) getOrHeadHandler(w http.ResponseWriter, r *http.Request
...
+			case len(pathSplit) == 4 && pathSplit[3] == "": // url: /ipfs/$hash/
+
+			// add the correct link depending on wether the path ends with a slash
+			default:
+				if strings.HasSuffix(backLink, "/") {
+					backLink += "./.."
+				} else {
+					backLink += "/.."
+				}
+			}
```
Comment (jbenet) [inline core/corehttp/gateway_handler.go]: :+1:

File: core/corehttp/gateway_indexPage.go (hunk 2 above)
Comment (jbenet) [inline core/corehttp/gateway_indexPage.go]: maybe put this in an actual template file and go-generate it into go? (nbd either way)

Comment (jbenet) [inline core/corehttp/gateway_indexPage.go]: can we use 2 spaces here? the double tabs + html deeeep nesting dont really get along.

File: core/corehttp/gateway_indexPage.go [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+												</td>
+												<td></td>
+										</tr>
+										{{ range .Listing }}
+										<tr>
+												<td>
+														<div class="ipfs-icon {{iconFromExt .Name}}">&nbsp;</div>
+												</td>
+												<td>
+														<a href="{{ .Path }}">{{ .Name }}</a>
```
Comment (jbenet) [inline core/corehttp/gateway_indexPage.go]: now that's some indentation

File: core/corehttp/gateway_indexPage.go (hunk 1 above)
Comment (jbenet) [inline core/corehttp/gateway_indexPage.go]: go generate too maybe?

Comment (jbenet) [inline core/corehttp/gateway_indexPage.go]: are the icons coming from a font?

Comment (jbenet) [inline core/corehttp/gateway_indexPage.go]: maybe we should use font-awesome here

Comment (jbenet) [inline core/corehttp/gateway_indexPage.go]: oh you already put them all in the css :+1: wfm.

File: core/corehttp/gateway_indexPage.go (hunk 2 above)
Comment (cryptix) [inline core/corehttp/gateway_indexPage.go]: I have good experience with [jteeuwen/go-bindata](https://github.com/jteeuwen/go-bindata) and [shurcooL/vfsgen](https://github.com/shurcooL/vfsgen) to embedd files with `go-generate`.

I just wasn't sure if we want this for a single file. I'll fix the indenting.

**Comment by jbenet** [comment]
> where to we seed the assets?

add them to https://github.com/ipfs/infrastructure/blob/master/seeding/refs-to-seed + get me to pin them.

> add tests. Do we have known/mocked hashes to test this a little? Basically I just want to test 404 and rendering without errors. 

> For testing the HTML we could use goquery

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d9febfa069fd7b613b6702c1762f15b63052f8c5
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by cryptix** [comment]
RFM

**Comment by whyrusleeping** [comment]
I really feel like the template should have zero external dependencies. Any css and javascript should be embedded IMO. If i dont have internet, all of a sudden my gateway wont work.

**Comment by cryptix** [comment]
> If i dont have internet, all of a sudden my gateway wont work.

Yea... that's correct..

Are the welcome examples seeded from the net or automagically added during init?
If we don't have something like that, i can inline them, too.

**Comment by whyrusleeping** [comment]
the welcome examples are seeded during init, i guess you could add them like that too if you want.

**Comment by cryptix** [comment]
I don't mind either way (or even adding new handlers) just don't want to waste effort.

cc @jbenet: what do you prefer?

**Comment by jbenet** [comment]
> the welcome examples are seeded during init, i guess you could add them like that too if you want.

this is the preferred approach. put all the files in the same root dir and pin that.

**Comment by jbenet** [comment]
@cryptix update?

**Comment by cryptix** [comment]
@jbenet waiting for #1419 (or rolling back to doc2go and embedding the css by hand)

**Comment by cryptix** [comment]
Assets are now seeded during (daemon) init. Also rebased for fun > ??? > profit ;)
