### PR TITLE
daemon: use fsrepo.IsInitialized to test for initialization

### LINKED ISSUE #3773: ipfs daemon --init does not work
#### Version information:

```
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/linux
Golang version: go1.8
```

#### Description:

I am passing `--init`, but it does not do what is saying it will do, which is, initialize the repo:

```
$ export IPFS_PATH=/ipfs
$ /usr/local/bin/ipfs daemon --init
Initializing daemon...
Error: no IPFS repo found in /ipfs.
please run: 'ipfs init'
```

### PR DESCRIPTION
**Pull request by kevina**
Use fsrepo.IsInitialized to test for initialization instead of just testing if the directory exists.

Also add test cases for '--init' option, including one the creates an empty directory.

Closes #3773.

### CODE REVIEW

File: test/sharness/t0063-daemon-init.sh [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+	'
+}
+
+test_expect_success "remove \$IPFS_PATH dir" '
+	rm -rf "$IPFS_PATH"
+'
+test_ipfs_daemon_init
+
+test_expect_success "create empty \$IPFS_PATH dir" '
+	rm -rf "$IPFS_PATH"
```
Comment (Kubuxu) [inline test/sharness/t0063-daemon-init.sh]: best to put `&&` after the rm, I know it "shouldn't" fail but still.

Comment (kevina) [inline test/sharness/t0063-daemon-init.sh]: Sorry.  The "&&" are too easy to forget about.

File: cmd/ipfs/daemon.go [hunk 2]
```diff
@@ -227,11 +226,7 @@ func daemonFunc(req cmds.Request, res cmds.Response) {
 
 	if initialize {
 
-		// now, FileExists is our best method of detecting whether ipfs is
-		// configured. Consider moving this into a config helper method
-		// `IsInitialized` where the quality of the signal can be improved over
-		// time, and many call-sites can benefit.
-		if !util.FileExists(req.InvocContext().ConfigRoot) {
+		if !fsrepo.IsInitialized(req.InvocContext().ConfigRoot) {
```
Comment (hoenirvili) [inline cmd/ipfs/daemon.go]: Instead of calling twice the ```req.InvocContex().ConfigRoot``` why not make under initialize something like 
```go
if initialize {
   cfg := req.InvocContext()
   if !fsrepo.IsInitialized(cfg) {
       err := initWithDefaults(os.Stdou, cfg)
// code
```

**Comment by kevina** [comment]
@whyrusleeping okay done

File: test/sharness/t0063-daemon-init.sh [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+test_ipfs_daemon_init() {
+	# Doing it manually since we want to launch the daemon with an
+	# empty or non-existent repo; the normal
+	# test_launch_ipfs_daemon does not work since it assumes the
+	# repo was created a particular way with regard to the API
+	# server.
+
+	test_expect_success "'ipfs daemon --init' succeeds" '
+		ipfs daemon --init >actual_daemon 2>daemon_err &
```
Comment (Kubuxu) [inline test/sharness/t0063-daemon-init.sh]: This will be problematic with other daemons people have running (port numbers). Not really sure how to solve it.

Comment (whyrusleeping) [inline test/sharness/t0063-daemon-init.sh]: Yeah... i'm not sure how to fix it either. We should look into adding a way to specify ports from here.

Though not sure if this should block the PR, Its probably a separate concern

Comment (kevina) [inline test/sharness/t0063-daemon-init.sh]: It will cause the test to fail on users machines who also have an IPFS daemon running.  Should we flag it some how?  If so I am not sure how.

Comment (Kubuxu) [inline test/sharness/t0063-daemon-init.sh]: We could check if ports from config are bound (8080, 4001, 5001) using netcat and if any of those are, skip the test. How that sounds?

Comment (whyrusleeping) [inline test/sharness/t0063-daemon-init.sh]: Yeah, lets do that. Its better to print a message about why it fails rather than just randomly failing.

Comment (whyrusleeping) [inline test/sharness/t0063-daemon-init.sh]: (lets not skip the test, I think its okay if it fails and says it needs those ports)

Comment (kevina) [inline test/sharness/t0063-daemon-init.sh]: @Kubuxu do you think you could push a commit, I am not familiar with `netcat`.  If not I figure it out tonight.

Comment (kevina) [inline test/sharness/t0063-daemon-init.sh]: Actually because I use a simple sleep and the init takes some time the test will pass as the daemon won't try to start right away.  I tested the tests with out my fix and the test fails because the daemon fails right away if there is a problem reading the repo.

If I up the timeout the daemon error output will make it fairly clear that there is a port conflict.
```
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
```
but you need to run the test with `-v`.

I am unsure how to use `netcat` to test for port conflict.  `netcat -w0 localhost 8080` does not work on my machine, I get "invalid wait-time 0".  Port testing doesn't seam like a documented use of `netcat` (at least the version (v1.10-41) I have installed on my machine) 

The sleep is 2 seconds now, I can lower it to 1 if you think it would be better.

Comment (whyrusleeping) [inline test/sharness/t0063-daemon-init.sh]: You should be able to use `nc -z -w1 localhost 5001`

Comment (kevina) [inline test/sharness/t0063-daemon-init.sh]: Do you still want to do that?  The test won't fail currently.

Comment (whyrusleeping) [inline test/sharness/t0063-daemon-init.sh]: @kevina Hrm... i think we can probably do without for now. Lets add a todo to add a flag for different ports on the daemon

Comment (kevina) [inline test/sharness/t0063-daemon-init.sh]: @whyrusleeping do you think we I should reduce the timeout to 1 sec to minimize the chance of this test failing?

Comment (whyrusleeping) [inline test/sharness/t0063-daemon-init.sh]: I wouldnt worry about it, lets just make a note to do proper port selection for this later.

**Comment by kevina** [comment]
I added a note as an issue.  This should be good to go...
