### PR TITLE
Pin ls traverses all indirect pins

### LINKED ISSUE #6527: Pin ls stops traversing recursive pins after hitting a direct pin
We should avoid re-emitting these directly pinned blocks but we still need to continue traversing the tree. This needs a _test_ to be considered fixed.

Regression from #6493.

### PR DESCRIPTION
**Pull request by aschmahmann**
1) Fixes #6527 
2) Deduplicates most of the pin ls code between the CoreAPI version and the commands version (the method is not optimal, but hopefully the CoreAPI will get a streaming option for `pin ls` soon and then this will be easy)
3) Introduces a precedence change for pin ls. A direct/recursive pin is now labeled as such even if also indirectly pinned. The previous precedence ordering was recursive > indirect > direct, it is now recursive/direct > indirect.

Changes 1 and 3 need to be tested, and I will submit a PR for a CoreAPI test (if we want a sharness test we can do that as well, but it seems like overkill). Since the CoreAPI tests all live in interface-go-ipfs-core this test should probably be there as well.

@Stebalien

### CODE REVIEW

**Comment by aschmahmann** [comment]
Ideally we should merge the tests (ipfs/interface-go-ipfs-core#47) before merging this so that we can reference the tests from go-ipfs. However, I'm not picky on ordering here as long as the tests actually end up running on the CoreAPI code.

File: core/commands/pin.go [hunk 1]
```diff
@@ -475,69 +477,46 @@ func pinLsKeys(req *cmds.Request, typeStr string, n *core.IpfsNode, api coreifac
...
 
-	keys := cid.NewSet()
-
-	AddToResultKeys := func(keyList []cid.Cid, typeStr string) error {
-		for _, c := range keyList {
-			if keys.Visit(c) {
-				err := emit(&PinLsOutputWrapper{
+	procErr := make(chan error, 1)
+	ctx := req.Context
+	go func() {
```
Comment (Stebalien) [inline core/commands/pin.go]: This goroutine is unnecessary.

File: core/coreapi/pin.go [hunk 2]
```diff
@@ -191,45 +192,104 @@ func (p *pinInfo) Type() string {
...
-	keys := make(map[cid.Cid]*pinInfo)
-
-	AddToResultKeys := func(keyList []cid.Cid, typeStr string) {
-		for _, c := range keyList {
-			keys[c] = &pinInfo{
-				pinType: typeStr,
-				path:    path.IpldPath(c),
+	var pins []coreiface.Pin
+	ctxError := make(chan error, 1)
+	go func() {
```
Comment (Stebalien) [inline core/coreapi/pin.go]: This goroutine is unnecessary.

File: core/commands/pin.go [hunk 3]
```diff
@@ -475,72 +477,40 @@ func pinLsKeys(req *cmds.Request, typeStr string, n *core.IpfsNode, api coreifac
...
-				if err != nil {
-					return err
-				}
+	procErr := make(chan error, 1)
+	ctx := req.Context
+	for {
+		select {
+		case p, ok := <-pinCh:
+			if !ok {
+				procErr <- nil
```
Comment (Stebalien) [inline core/commands/pin.go]: Unnecessary channel?

File: core/coreapi/pin.go [hunk 4]
```diff
@@ -191,45 +192,96 @@ func (p *pinInfo) Type() string {
...
-		for _, k := range api.pinning.RecursiveKeys() {
-			err := merkledag.Walk(
-				ctx, merkledag.GetLinksWithDAG(api.dag), k,
-				set.Visit,
-				merkledag.SkipRoot(), merkledag.Concurrent(),
-			)
-			if err != nil {
-				return nil, err
+	go func() {
+		defer close(ch)
```
Comment (Stebalien) [inline core/coreapi/pin.go]: Given the way this function is currently called, this can hide errors: we can observe this channel closing before we read the error off the error channel.

It's generally safer to just use a "result" channel. That makes it easier to call this function as the `for x := range myCh` syntax can be used.

Comment (Stebalien) [reply core/coreapi/pin.go]: Alternatively, we can close both the error and normal channels and, instead of listening on the error channel, run `err := <-errCh` after finishing the _normal_ loop.

File: core/coreapi/pin.go [hunk 5]
```diff
@@ -191,45 +192,96 @@ func (p *pinInfo) Type() string {
...
+				for _, k := range pin.RecursiveKeys() {
+					keys.Add(k)
+				}
+			}
+			indirectKeys := cid.NewSet()
+			for _, k := range pin.RecursiveKeys() {
+				err := merkledag.Walk(ctx, merkledag.GetLinksWithDAG(dag), k, func(c cid.Cid) bool {
+					r := indirectKeys.Visit(c)
+					if r && keys.Visit(c) {
+						ch <- &pinInfo{
```
Comment (Stebalien) [inline core/coreapi/pin.go]: This can block.

**Comment by Stebalien** [comment]
@aschmahmann bump (when you get a chance).

File: core/coreapi/pin.go (hunk 4 above)
Comment (aschmahmann) [reply core/coreapi/pin.go]: I think I did what you asked here, lmk.

File: core/coreapi/pin.go (hunk 5 above)
Comment (aschmahmann) [reply core/coreapi/pin.go]: now checks on context

File: core/commands/pin.go (hunk 3 above)
Comment (aschmahmann) [reply core/commands/pin.go]: yep, I think a mistake from a some git mistakes. thx for the catch.

**Comment by aschmahmann** [comment]
@Stebalien I think we should just squash these commits when we're ready for merge. Lmk and we can finish any last issues with this PR.

File: core/coreapi/pin.go [hunk 6]
```diff
@@ -194,57 +195,119 @@ func (p *pinInfo) Type() string {
...
+			if err != nil {
+				errCh <- err
+				return
+			}
 
-	out := make([]coreiface.Pin, 0, len(keys))
-	for _, v := range keys {
-		out = append(out, v)
-	}
+			if typeStr != "all" {
```
Comment (Stebalien) [inline core/coreapi/pin.go]: This needs a comment explaining _why_ we're doing this.

Comment (Stebalien) [reply core/coreapi/pin.go]: I also inverted the test to `if typeStr == "indirect"` to make it clear that we're skipping this because we only care about indirect pins.
