### PR TITLE
fix panic in bitswap working limit spawning

### LINKED ISSUE #1857: bitswap workers panic in tests
I keep seeing this issue: https://circleci.com/gh/ipfs/go-ipfs/1596

Another goprocess limiter issue.

### PR DESCRIPTION
**Pull request by whyrusleeping**
fixes #1857 

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

File: exchange/bitswap/workers.go [hunk 1]
```diff
@@ -74,43 +73,48 @@ func (bs *Bitswap) taskWorker(ctx context.Context, id int) {
 
 func (bs *Bitswap) provideWorker(px process.Process) {
 
-	limiter := ratelimit.NewRateLimiter(px, provideWorkerMax)
+	limit := make(chan struct{}, provideWorkerMax)
 
 	limitedGoProvide := func(k key.Key, wid int) {
+		go func() {
```
Comment (jbenet) [inline exchange/bitswap/workers.go]: defer ?

Comment (whyrusleeping) [inline exchange/bitswap/workers.go]: oh. right. thats the word i was looking for...
