### PR TITLE
Return 404 Not Found for failed path resolutions

### LINKED ISSUE #2286: /api/v0/dns/ returns HTTP 500  instead of 404 when dnslink is not found
This is a cosmetic issue. :bouquet: 
## 

I implemented PoC for https://github.com/lidel/ipfs-firefox-addon/issues/44  and noticed that lookups for FQDNs without `dnslink`  produce HTTP 500:

> 2016-02-02-223121_822x400_scrot

After `ipfs log level namesys debug`  I see:

```
21:31:01.708  INFO    namesys: DNSResolver resolving upt.graphiq.com dns.go:54
21:31:01.749 WARNI    namesys: Could not resolve upt.graphiq.com base.go:21
21:31:03.627  INFO    namesys: DNSResolver resolving gscounters.us1.gigya.com dns.go:54
21:31:03.668 WARNI    namesys: Could not resolve gscounters.us1.gigya.com base.go:21
21:31:05.714  INFO    namesys: DNSResolver resolving adx.adnxs.com dns.go:54
21:31:05.761 WARNI    namesys: Could not resolve adx.adnxs.com base.go:21
21:31:13.095  INFO    namesys: DNSResolver resolving perpro17-ew1b.ml314.com dns.go:54
21:31:13.136 WARNI    namesys: Could not resolve perpro17-ew1b.ml314.com base.go:21
```

It is easy to reproduce via curl:

```
curl -vq http://localhost:5001/api/v0/dns/1.gravatar.com                                         ~
*   Trying ::1...
* Connected to localhost (::1) port 5001 (#0)
> GET /api/v0/dns/1.gravatar.com HTTP/1.1
> Host: localhost:5001
> User-Agent: curl/7.45.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output
< Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output
< Content-Type: application/json
< Trailer: X-Stream-Error
< Transfer-Encoding: chunked
< Date: Tue, 02 Feb 2016 21:57:16 GMT
< Transfer-Encoding: chunked
< 
{"Message":"lookup 1.gravatar.com on 8.8.8.8:53: no such host","Code":0}
```

My problem: broken semantics. There was no Internal Server Error. Everything worked as expected. :ok_hand: 

DNS Lookup that does not find `dnslink` should return a code in lower range, probably the best one being  HTTP 404 (Not Found) or 400 (Bad Request).

A similar issue: https://github.com/ipfs/go-ipfs/issues/1047

### PR DESCRIPTION
**Pull request by lgierth**
Fixes #2286 -- bonus: also kills gateway's namesys dependency

**But:** I just noticed that the CLI assumes "command not found" for 404 responses. Great.

### CODE REVIEW

File: core/corehttp/gateway_handler.go [hunk 1]
```diff
@@ -162,26 +161,18 @@ func (i *gatewayHandler) getOrHeadHandler(ctx context.Context, w http.ResponseWr
...
-			w.WriteHeader(http.StatusServiceUnavailable)
-			fmt.Fprint(w, "Could not resolve path. Node is in offline mode.")
+			webError(w, "ipfs cat "+urlPath, err, http.StatusServiceUnavailable)
 			return
 		}
 		fallthrough
 	default:
-		// all other erros
-		webError(w, "Path Resolve error", err, http.StatusBadRequest)
+		webError(w, "ipfs cat "+urlPath, err, http.StatusNotFound)
```
Comment (Kubuxu) [inline core/corehttp/gateway_handler.go]: I think it should mention error here. HTTP codes are hidden in browser.

Comment (lgierth) [inline core/corehttp/gateway_handler.go]: The printed message contains `err`, so it's gonna be something like: "ipfs cat /ipns/foo.com: Could not resolve name"

Comment (Kubuxu) [inline core/corehttp/gateway_handler.go]: Ahh, I have missed that.

**Comment by whyrusleeping** [comment]
@lgierth So running `ipfs dns DoesNotExist.not.a.domain` will return 'command not found' ?

**Comment by lgierth** [comment]
Note: I'll amend this to return a different error "Code" in the response, instead of hijacking the http status code.

**Comment by lgierth** [comment]
> Note: I'll amend this to return a different error "Code" in the response, instead of hijacking the http status code.

done

**Comment by lgierth** [comment]
Checking why CI is upset

**Comment by lgierth** [comment]
Travis and Circle are happy now -- I didn't bother restarting the second Travis build though.

**Comment by lgierth** [comment]
Wait this isn't quite right

**Comment by lgierth** [comment]
Nevermind, I tested with the wrong binary. It does correctly return `{"Message":"Could not resolve name.","Code":2}` for `ipfs dns foo.com`.
