### PR TITLE
Publish by path

### LINKED ISSUE #749: `ipfs name publish` should take a path
```
> ipfs name publish /ipfs/QmPtgR1KTjug9EHGgXzt7RQ5umcJ6MwVkYQSkr5VABNeyu/cat.jpg
Error: publish value must be str multihash. multihash too short. must be > 3 bytes
```

### PR DESCRIPTION
**Pull request by AtnNn**
Fixes #749

```
$ ipfs name publish /ipfs/QmV32WjiHoYMC5xTuiwZMcEFx686M7qKJmbMQ1cSEwkXvU/foo
Published name QmXmPBXfviRCFdcuVF9xn6VVwNgAXoKMc2majbbDKPvkZ3 to QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6
```

### CODE REVIEW

File: core/commands/publish.go [hunk 1]
```diff
@@ -71,21 +72,32 @@ Publish a <ref> to another public key:
...
+
+		hash, err := node.Multihash()
+		if err != nil {
+			res.SetError(err, cmds.ErrNormal)
+			return
 		}
 
 		// TODO n.Keychain.Get(name).PrivKey
-		output, err := publish(n, n.PrivateKey, ref)
+		output, err := publish(n, n.PrivateKey, hash.B58String())
```
Comment (jbenet) [inline core/commands/publish.go]: can use:

```go
key, err := node.Key()
if err != nil {
    res.SetError(err, cmds.ErrNormal)
    return
}

output, err := publish(n, n.PrivateKey, key.Pretty())
```

So that if we change our "key pretty-printing" it will change here too.

**Comment by jbenet** [comment]
@AtnNn great! this LGTM, thanks. one minor comment above, and the tests don't pass: https://travis-ci.org/ipfs/go-ipfs/jobs/58170171#L2308

- [ ] use `key.Pretty()`
- [ ] pass tests

(looking into why the tests dont pass atm)

**Comment by jbenet** [comment]
@AtnNn thanks! LGTM. i'll merge when travis finishes running

**Comment by AtnNn** [comment]
@jbenet thanks. I ammended

* your changes to the tests
* use `key.Pretty()`
* and an improved error message

**Comment by jbenet** [comment]
thank you for the PR @AtnNn !
