### PR TITLE
pre-populate required arguments from request body

### LINKED ISSUE #4823: panic in handler
682b263f3a54ffa36409422d922e80adead87e0c

~~I'm not sure what triggered this, it may have been when opening a hash via the gateway.~~ I'm guessing `/core/commands/publish.go:96` is the problem point causing an out of range but it could be elsewhere here.

```
Daemon is ready
18:55:51.133 ERROR  providers: base32 decoding error: illegal base32 data at input byte 55 providers.go:102
...
07:55:37.541 ERROR  providers: base32 decoding error: illegal base32 data at input byte 55 providers.go:102
08:32:43.324 ERROR  cmds/http: a panic has occurred in the commands handler! asm_amd64.s:573
08:32:43.326 ERROR  cmds/http: runtime error: index out of range asm_amd64.s:573
08:32:43.327 ERROR  cmds/http: stack trace:
goroutine 56483732 [running]:
runtime/debug.Stack(0xc0422269a0, 0xc0d0070f50, 0x1)
        C:/Go/src/runtime/debug/stack.go:24 +0xae
gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds/http.(*handler).ServeHTTP.func1()
        C:/Users/Dominic/Projects/Go/src/gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds/http/handler.go:94 +0x130
panic(0xcef380, 0x1548c00)
        C:/Go/src/runtime/panic.go:505 +0x237
github.com/ipfs/go-ipfs/core/commands.glob..func96(0x1002d40, 0xc0c65ad2e0, 0x1001b20, 0xc0a851ec30)
        C:/Users/Dominic/Projects/Go/src/github.com/ipfs/go-ipfs/core/commands/publish.go:96 +0x7a5
github.com/ipfs/go-ipfs/commands/legacy.NewCommand.func1(0xc0c5dd3dc0, 0x4f0f84d0, 0xc0c5dd3e30, 0xfed4e0, 0xc0a721ac40)
        C:/Users/Dominic/Projects/Go/src/github.com/ipfs/go-ipfs/commands/legacy/command.go:38 +0x1be
gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds.(*Command).Call(0x1557580, 0xc0c5dd3dc0, 0x4f0f84d0, 0xc0c5dd3e30, 0xfed4e0, 0xc0a721ac40)
        C:/Users/Dominic/Projects/Go/src/gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds/command.go:106 +0x24d
gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds/http.(*handler).ServeHTTP(0xc09a1aa9a0, 0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Users/Dominic/Projects/Go/src/gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds/http/handler.go:160 +0x8d9
gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds/http.prefixHandler.ServeHTTP(0xe1154f, 0x7, 0xfedea0, 0xc09a1aa9a0, 0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Users/Dominic/Projects/Go/src/gx/ipfs/QmabLouZTZwhfALuBcssPvkzhbYGMb4394huT7HY4LQ6d3/go-ipfs-cmds/http/apiprefix.go:24 +0xcf
gx/ipfs/QmPG2kW5t27LuHgHnvhUwbHCNHAt2eUcb4gPHqofrESUdB/cors.(*Cors).Handler.func1(0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Users/Dominic/Projects/Go/src/gx/ipfs/QmPG2kW5t27LuHgHnvhUwbHCNHAt2eUcb4gPHqofrESUdB/cors/cors.go:188 +0x105
net/http.HandlerFunc.ServeHTTP(0xc09a1aa9e0, 0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Go/src/net/http/server.go:1947 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc07ccfa540, 0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Go/src/net/http/server.go:2337 +0x137
github.com/ipfs/go-ipfs/core/corehttp.CheckVersionOption.func1.1(0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Users/Dominic/Projects/Go/src/github.com/ipfs/go-ipfs/core/corehttp/commands.go:175 +0x129
net/http.HandlerFunc.ServeHTTP(0xc09a1aa920, 0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Go/src/net/http/server.go:1947 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0421f9440, 0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Go/src/net/http/server.go:2337 +0x137
net/http.(Handler).ServeHTTP-fm(0xff6c40, 0xc0b5344518, 0xc0c49d0d00)
        C:/Go/src/net/http/h2_bundle.go:5475 +0x54
gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0xff77c0, 0xc0dc447ce0, 0xc0c49d0d00)
        C:/Users/Dominic/Projects/Go/src/gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus/http.go:287 +0x276
net/http.HandlerFunc.ServeHTTP(0xc07ce688c0, 0xff77c0, 0xc0dc447ce0, 0xc0c49d0d00)
        C:/Go/src/net/http/server.go:1947 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0421f92c0, 0xff77c0, 0xc0dc447ce0, 0xc0c49d0d00)
        C:/Go/src/net/http/server.go:2337 +0x137
net/http.serverHandler.ServeHTTP(0xc07d140000, 0xff77c0, 0xc0dc447ce0, 0xc0c49d0d00)
        C:/Go/src/net/http/server.go:2694 +0xc3
net/http.(*conn).serve(0xc0c7488f00, 0xff8a40, 0xc0a8873b80)
        C:/Go/src/net/http/server.go:1830 +0x658
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2795 +0x282
 asm_amd64.s:573
08:55:46.372 ERROR  providers: base32 decoding error: illegal base32 data at input byte 55 providers.go:102
```

### PR DESCRIPTION
**Pull request by Stebalien**
This way, we can always assume that indexing a required argument works.

Also:

* test that the command tree doesn't have any obvious bugs (duplicate options, arguments in the wrong order, etc).
* simplify the usage ParseBodyArgs.

fixes #4823

### CODE REVIEW

**Comment by Stebalien** [comment]
This looks bad:

```
  
ok 78 - 'ipfs add -r --raw-leaves' output looks good

expecting success: 
    { echo "$MARS"; echo "$VENUS"; } | ipfs cat >actual
  
ok 79 - ipfs cat accept many hashes from built input

expecting success: 
    cat mountdir/planets/mars.txt mountdir/planets/venus.txt >expected &&
    test_cmp expected actual
  
> diff -u expected actual
--- expected	2018-03-17 21:04:04.055381963 +0000
+++ actual	2018-03-17 21:04:04.043382082 +0000
@@ -1,2 +1 @@
 Hello Mars!
```

**Comment by Stebalien** [comment]
So, the problem here is that the client is reading off one arg and then forwarding that to the server. However, I've replaced `Files` with `nil` so we don't forward the rest to the server.

**Comment by Stebalien** [comment]
So, the question here is, *should* we check the arguments on the client? Probably but, in that case, we're going to be splitting them (passing one via the query string and the rest via the body).

**Comment by whyrusleeping** [comment]
> we're going to be splitting them (passing one via the query string and the rest via the body).

This actually seems reasonable. It moves us towards having the requirement that all required arguments are specified via the query string, and the body is only used for optional/variadic args

**Comment by whyrusleeping** [comment]
> However, I've replaced Files with nil so we don't forward the rest to the server.

Wait up, i must have missed this in the CR. We should just replace files with the next file.

**Comment by Stebalien** [comment]
Blocked on https://github.com/ipfs/go-ipfs-cmds/pull/83

File: test/sharness/t0090-get.sh [hunk 1]
```diff
@@ -177,9 +177,7 @@ test_get_cmd
 
 test_expect_success "empty request to get doesn't panic and returns error" '
   curl "http://$API_ADDR/api/v0/get" > curl_out || true &&
-    grep "not enough arugments provided" curl_out
-
-
+    grep "argument \"ipfs-path\" is required" curl_out
```
Comment (whyrusleeping) [inline test/sharness/t0090-get.sh]: thats a much better error message.
