### PR TITLE
namesys: Make paths with multiple segemnts work. Fixes #2059

### LINKED ISSUE #2059: Doesn't resolve dnslink's child link
```sh
$ curl ipfs.io -H 'Host: blog.ipfs.io'
404 page not found
$ ipfs resolve -r /ipns/blog.ipfs.io
Error: could not resolve name.
$ dig +short TXT blog.ipfs.io
"dnslink=/ipns/ipfs.io/blog"

$ ipfs resolve -r /ipns/ipfs.io/blog
Error: merkledag: not found
```

The last one is the actual bug I think, the others are just the bug bubbling up.

Although on the gateway, it works:

```sh
$ curl ipfs.io/ipns/ipfs.io/blog
<a href="/ipns/ipfs.io/blog/">Found</a>.
```

This is what it should be resolving:

```sh
$ ipfs ls /ipns/ipfs.io
QmTkQCrspeQDEiFBvphH3ULHYNWr3aXpymGiyjMrrUimtZ 1717422 blog/
QmUjToECfdVyd5GsM53Nw5FJqiejx1uEzeMwvdhP88jgM7 134463  docs/
QmPLFGjmAqEXCU4GrYgT7JmhDP17fD3NdPgNEfXevfWzAm 12265   index.html
QmNXFHU3KzhzXN9pZ5Bdghk3LYGj58Xzi7WvMVVoykdLxA 136279  media/
QmU2NBSYkbHZmnYeJUSkLqirR7W3LtsBrxv1W8Zu22an3D 6439748 styles/
```

And thus the expected output of the buggy resolve command is:

```sh
$ ipfs resolve -r /ipns/ipfs.io/blog
/ipfs/QmTkQCrspeQDEiFBvphH3ULHYNWr3aXpymGiyjMrrUimtZ
```

### PR DESCRIPTION
**Pull request by Kubuxu**
Also fixes non-recursive resolve erring instead showing one step.

The patch of `core/commands/resolve.go` could be done better but I don't know how to get access to `ErrResolveRecursion`.

It allows for dnslinks into sub-segments. So ie. hosting multiple blogs on just domains from one pubkey.

Fixes #2059

### CODE REVIEW

**Comment by Kubuxu** [comment]
Added tests, fixed one more case and rebased.

**Comment by Kubuxu** [comment]
Should I recreate the PR for dev0.4.0 branch?

File: core/commands/resolve.go [hunk 1]
```diff
@@ -82,12 +82,15 @@ Resolve the value of an IPFS DAG path:
 		// the case when ipns is resolved step by step
 		if strings.HasPrefix(name, "/ipns/") && !recursive {
 			p, err := n.Namesys.ResolveN(req.Context(), name, 1)
+
+			if p != "" {
```
Comment (whyrusleeping) [inline core/commands/resolve.go]: I dont like treating this as a special case... If we call the path resolved, the error should be nil.

Comment (Kubuxu) [inline core/commands/resolve.go]: I don't like it too but in other case there is no reason to have resolve without recursion.

You can't use it to do step by step resolving as you just get error of recursion exceeded.
I will remove this from the PR as this is something that might require some refactoring to get right.

**Comment by Kubuxu** [comment]
I've removed the change to the command.

**Comment by whyrusleeping** [comment]
@Kubuxu we don't seem to test for `domain.tld/path/below/that`. Could you add a couple of those types of tests? Also, could you add a test for the domain resolving to something like:
`/ipns/HASH/` with the trailing slash, as well as `/ipns/HASH/path/` also with the trailing slash

**Comment by Kubuxu** [comment]
I've added more tests and resolved issues with trailing slashes. Thanks for pointing this out.

I can squash commits if you want.

**Comment by whyrusleeping** [comment]
no worries about squashing

**Comment by whyrusleeping** [comment]
@Kubuxu just as a sanity check, you've tested this with real world dns resultion once or twice, right?

**Comment by whyrusleeping** [comment]
this LGTM

**Comment by Kubuxu** [comment]
I did. http://hastebin.com/inorefagip.txt

`wget localhost:8080/ipns/ipfs2.kubuxu.ovh/main.css` also works.

**Comment by whyrusleeping** [comment]
awesome, this LGTM
